services:
  google-maps-scraper:
    build: .
    container_name: gmaps-scraper
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gmaps_data:/gmapsdata
      - gmaps_cache:/opt

volumes:
  gmaps_data:
  gmaps_cache:
