services:
  google-maps-scraper:
    build: .
    restart: unless-stopped
    command: ["-web", "-data-folder", "/gmapsdata"]
    ports:
      - "8080:8080"
    volumes:
      - gmaps_data:/gmapsdata
      - gmaps_cache:/opt

volumes:
  gmaps_data:
  gmaps_cache:
