services:
  scraper-ui:
    build: .
    restart: unless-stopped
    container_name: scraper-web-ui
    ports:
      - "8090:8080"
    volumes:
      - scraper_data:/gmapsdata
      - scraper_cache:/opt

volumes:
  scraper_data:
  scraper_cache:
